# Generated by Django 4.1.3 on 2023-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
