# Generated by Django 4.1.3 on 2023-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_integrations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_integrations',
            field=models.BooleanField(default=False),
        ),
    ]
